services:
  shortstack-client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "5050:5050"
  shortstack-authorization-server:
    build:
      context: .
      dockerfile: ./docker/authorization-server/Dockerfile
    ports:
      - "5051:5051"
  shortstack-api-server:
    build:
      context: .
      dockerfile: ./docker/api-server/Dockerfile
    ports:
      - "5052:5052"
